[theme]
primaryColor = "#d45608"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[client]
toolbarMode = "viewer"
showSidebarNavigation = false